// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryDemo;

namespace RepositoryDemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RepositoryDemo.DbModel.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasColumnName("category_name")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<long>("CreaterId")
                        .HasColumnName("creater_id");

                    b.Property<DateTime>("UpdateTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("update_time");

                    b.Property<long>("UpdaterId")
                        .HasColumnName("updater_id");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.IdTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("requestType");

                    b.HasKey("Id");

                    b.ToTable("IdTest");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.Passage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<long>("CreaterId")
                        .HasColumnName("creater_id");

                    b.Property<DateTime>("LastEditTime")
                        .HasColumnName("last_edit_time");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasMaxLength(30);

                    b.Property<DateTime>("UpdateTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("update_time");

                    b.Property<long>("UpdaterId")
                        .HasColumnName("updater_id");

                    b.HasKey("Id");

                    b.ToTable("passage");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.PassageCategory", b =>
                {
                    b.Property<long>("PassageId")
                        .HasColumnName("passage_id");

                    b.Property<long>("CategoryId")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<long>("CreaterId")
                        .HasColumnName("creater_id");

                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdateTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("update_time");

                    b.Property<long>("UpdaterId")
                        .HasColumnName("updater_id");

                    b.HasKey("PassageId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("passage_category");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("AA2")
                        .HasColumnName("a_a2")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<long>("CreaterId")
                        .HasColumnName("creater_id");

                    b.Property<decimal>("Score")
                        .HasColumnName("score")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StudentName")
                        .HasColumnName("student_name")
                        .HasMaxLength(30);

                    b.Property<string>("Test")
                        .HasColumnName("test")
                        .HasMaxLength(30);

                    b.Property<DateTime>("UpdateTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("update_time");

                    b.Property<long>("UpdaterId")
                        .HasColumnName("updater_id");

                    b.HasKey("Id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.StudentAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .HasColumnName("address1")
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<long>("CreaterId")
                        .HasColumnName("creater_id");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasMaxLength(30);

                    b.Property<long>("StudentId")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdateTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("update_time");

                    b.Property<long>("UpdaterId")
                        .HasColumnName("updater_id");

                    b.Property<int>("Zipcode")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("student_address");
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.PassageCategory", b =>
                {
                    b.HasOne("RepositoryDemo.DbModel.Category", "Category")
                        .WithMany("PassageCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RepositoryDemo.DbModel.Passage", "Passage")
                        .WithMany("PassageCategories")
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RepositoryDemo.DbModel.StudentAddress", b =>
                {
                    b.HasOne("RepositoryDemo.DbModel.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("RepositoryDemo.DbModel.StudentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
